// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/priscila-albertini-da-silva/item-detail-ml/internal/domain"
	delivery "github.com/priscila-albertini-da-silva/item-detail-ml/internal/handler/delivery"

	mock "github.com/stretchr/testify/mock"
)

// ProductUseCase is an autogenerated mock type for the ProductUseCase type
type ProductUseCase struct {
	mock.Mock
}

// GetAll provides a mock function with no fields
func (_m *ProductUseCase) GetAll() ([]domain.ProductItem, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.ProductItem
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ProductItem, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ProductItem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductItem)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: productID
func (_m *ProductUseCase) GetProduct(productID string) (*domain.ProductItem, error) {
	ret := _m.Called(productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *domain.ProductItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.ProductItem, error)); ok {
		return rf(productID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.ProductItem); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductDetails provides a mock function with given fields: productID
func (_m *ProductUseCase) GetProductDetails(productID string) (*delivery.ItemProductResponse, error) {
	ret := _m.Called(productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductDetails")
	}

	var r0 *delivery.ItemProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*delivery.ItemProductResponse, error)); ok {
		return rf(productID)
	}
	if rf, ok := ret.Get(0).(func(string) *delivery.ItemProductResponse); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*delivery.ItemProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductUseCase creates a new instance of ProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductUseCase {
	mock := &ProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
