// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/priscila-albertini-da-silva/item-detail-ml/internal/domain"
	delivery "github.com/priscila-albertini-da-silva/item-detail-ml/internal/handler/delivery"

	mock "github.com/stretchr/testify/mock"
)

// ItemProductResponseFactory is an autogenerated mock type for the ItemProductResponseFactory type
type ItemProductResponseFactory struct {
	mock.Mock
}

// ToItemProductResponse provides a mock function with given fields: p, pm
func (_m *ItemProductResponseFactory) ToItemProductResponse(p domain.ProductItem, pm []domain.PaymentMethod) *delivery.ItemProductResponse {
	ret := _m.Called(p, pm)

	if len(ret) == 0 {
		panic("no return value specified for ToItemProductResponse")
	}

	var r0 *delivery.ItemProductResponse
	if rf, ok := ret.Get(0).(func(domain.ProductItem, []domain.PaymentMethod) *delivery.ItemProductResponse); ok {
		r0 = rf(p, pm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*delivery.ItemProductResponse)
		}
	}

	return r0
}

// NewItemProductResponseFactory creates a new instance of ItemProductResponseFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemProductResponseFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemProductResponseFactory {
	mock := &ItemProductResponseFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
